[2019-Dec-02 21:22] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /easyui? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /static/css/images/combo_arrow.png? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /static/css/images/blank.gif? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:23] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:24] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:24] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:24] 127.0.0.1 GET http /result?data=%5B%7B%22IP%22%3A%221.1.1.1%22%2C%22CONFIG1%22%3A%22blah%22%2C%22CONFIG2%22%3A%22bleh%22%7D%2C%7B%22IP%22%3A%222.2.2.2%22%2C%22CONFIG1%22%3A%22blah2%22%2C%22CONFIG2%22%3A%22bleh2%22%7D%2C%7B%22IP%22%3A%223.3.3.3%22%2C%22CONFIG1%22%3A%22blah3%22%2C%22CONFIG2%22%3A%22bleh3%22%7D%5D 200 OK
[2019-Dec-02 21:24] 127.0.0.1 GET http /TechType_fix_config?data=%7B%22ipaddress%22%3A%22%5B%5C%221.1.1.1%5C%22%5D%22%2C%22package%22%3A%22%5B%5D%22%7D 200 OK
[2019-Dec-02 21:28] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:28] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:29] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:29] 127.0.0.1 GET http /static/favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:29] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:29] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 21:29] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:29] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:29] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:30] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:30] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:31] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:31] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:31] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:32] 127.0.0.1 GET http /result?data=%5B%7B%22IP%22%3A%221.1.1.1%22%2C%22CONFIG1%22%3A%22blah%22%2C%22CONFIG2%22%3A%22bleh%22%7D%2C%7B%22IP%22%3A%222.2.2.2%22%2C%22CONFIG1%22%3A%22blah2%22%2C%22CONFIG2%22%3A%22bleh2%22%7D%2C%7B%22IP%22%3A%223.3.3.3%22%2C%22CONFIG1%22%3A%22blah3%22%2C%22CONFIG2%22%3A%22bleh3%22%7D%5D 200 OK
[2019-Dec-02 21:32] 127.0.0.1 GET http /TechType_fix_config?data=%7B%22ipaddress%22%3A%22%5B%5C%221.1.1.1%5C%22%5D%22%2C%22package%22%3A%22%5B%5D%22%7D 200 OK
[2019-Dec-02 21:32] 127.0.0.1 GET http /test? 200 OK
[2019-Dec-02 21:32] 127.0.0.1 GET http /test_js? 200 OK
[2019-Dec-02 21:32] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:33] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /test? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /test_js? 200 OK
[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:37] 127.0.0.1 GET http /test? 200 OK
[2019-Dec-02 21:37] 127.0.0.1 GET http /test_js? 200 OK
[2019-Dec-02 21:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:37] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-02 21:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:37] 127.0.0.1 GET http /test? 200 OK
[2019-Dec-02 21:37] 127.0.0.1 GET http /test_js? 200 OK
[2019-Dec-02 21:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:37] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:38] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:38] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:46] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 GET http /fetch? 200 OK
[2019-Dec-02 21:47] 127.0.0.1 GET http /form_process?q= 200 OK
[2019-Dec-02 21:48] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:48] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-02 21:48] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:48] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:49] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:49] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:50] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:50] 127.0.0.1 GET http /array_test? 200 OK
[2019-Dec-02 21:50] 127.0.0.1 POST http /array_test? 200 OK
[2019-Dec-02 21:50] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:51] 127.0.0.1 GET http /easyui? 200 OK
[2019-Dec-02 21:51] 127.0.0.1 GET http /static/css/images/combo_arrow.png? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:51] 127.0.0.1 GET http /static/css/images/blank.gif? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:51] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-02 21:51] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:55] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 21:58] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:01] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:02] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:04] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:05] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:07] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:09] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:10] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:11] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-02 22:15] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-06 20:16] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/css/auto-complete.css? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/css/signin.css? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/js/script.js? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/js/fetch.js? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/css/my_style.css? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/data/data.json? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/css/scss_css.css? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/js/auto-complete.min.js? 304 NOT MODIFIED
[2019-Dec-06 20:16] 127.0.0.1 GET http /static/js/autocomplete.js? 304 NOT MODIFIED
[2019-Dec-06 20:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:20] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:21] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:21] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:21] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:21] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 20:21] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:21] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:23] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:25] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 20:25] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /easyui? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/easyui.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/icon.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/demo.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/jquery.min.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/jquery.easyui.min.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/images/combo_arrow.png? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/images/blank.gif? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:26] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:27] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:27] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:32] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:32] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:34] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:37] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:37] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 20:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:50] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:50] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 20:50] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:56] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:56] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:56] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 20:56] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:57] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:57] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 20:57] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 20:57] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:14] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:14] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:14] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:14] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:31] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:32] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:34] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-06 21:35] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-06 21:36] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:36] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 21:36] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:40] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:40] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 21:40] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:44] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:44] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-06 21:44] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:47] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:47] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-06 21:50] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:50] 127.0.0.1 GET http /? 200 OK
[2019-Dec-06 21:50] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-06 21:50] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 15:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 15:38] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/css/auto-complete.css? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/css/my_style.css? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/css/signin.css? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/css/bootstrap.min.css? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/js/script.js? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/js/fetch.js? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/data/data.json? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /static/js/auto-complete.min.js? 304 NOT MODIFIED
[2019-Dec-07 15:38] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-07 15:38] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:06] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-07 16:06] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 16:06] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-07 16:06] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 16:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:06] 127.0.0.1 GET http /static/css/scss_css.css? 304 NOT MODIFIED
[2019-Dec-07 16:06] 127.0.0.1 GET http /static/js/autocomplete.js? 304 NOT MODIFIED
[2019-Dec-07 16:19] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:19] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 16:19] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:19] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:19] 127.0.0.1 GET http /? 200 OK
